version: '3.8'

services:
  headscale:
    image: ${HEADSCALE_IMAGE:-ghcr.io/juanfont/headscale:latest}
    container_name: ${HEADSCALE_NAME:-headscale}
    command: serve
    ports:
      - "${HEADSCALE_HTTP_PORT:-6888}:8080"
      - "${HEADSCALE_STUN_PORT:-3478}:3478/udp"
    volumes:
      - "${DATA_PATH:-/opt/containers/sys}/headscale/config.yaml:/etc/headscale/config.yaml"
      - "${DATA_PATH:-/opt/containers/sys}/headscale/data:/var/lib/headscale"
    restart: unless-stopped
    networks:
      - ztcloud

  etcd:
    image: ${ETCD_IMAGE:-quay.io/coreos/etcd:latest}
    container_name: ${ETCD_NAME:-etcd}
    ports:
      - "${ETCD_CLIENT_PORT:-2379}:2379"
    volumes:
      - "${DATA_PATH:-/opt/containers/sys}/etcd:/etcd-data"
    command: >
      /usr/local/bin/etcd --data-dir=/etcd-data --name ${ETCD_NODE_NAME:-node1}
      --initial-advertise-peer-urls http://etcd:2380
      --listen-peer-urls http://0.0.0.0:2380
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --initial-cluster ${ETCD_NODE_NAME:-node1}=http://etcd:2380
      --initial-cluster-token ${ETCD_CLUSTER_TOKEN:-etcd-cluster-1}
      --initial-cluster-state new
    restart: unless-stopped
    networks:
      - ztcloud

  coredns:
    image: ${COREDNS_IMAGE:-docker.io/coredns/coredns:1.11.1}
    container_name: ${COREDNS_NAME:-coredns}
    command: -conf /etc/coredns/Corefile
    ports:
      - "${COREDNS_TCP_PORT:-53}:53/tcp"
      - "${COREDNS_UDP_PORT:-53}:53/udp"
    volumes:
      - "${DATA_PATH:-/opt/containers/sys}/coredns/Corefile:/etc/coredns/Corefile"
      - "${DATA_PATH:-/opt/containers/sys}/coredns/hosts:/etc/coredns/hosts"
    restart: unless-stopped
    networks:
      - ztcloud
    depends_on:
      - etcd

  caddy:
    image: ${CADDY_IMAGE:-docker.io/library/caddy:latest}
    container_name: ${CADDY_NAME:-caddy}
    command: caddy run --config /etc/caddy/Caddyfile.json
    ports:
      - "${CADDY_ADMIN_PORT:-2019}:2019"
      - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - "${DATA_PATH:-/opt/containers/sys}/caddy/data:/data"
      - "${DATA_PATH:-/opt/containers/sys}/caddy/Caddyfile.json:/etc/caddy/Caddyfile.json"
    restart: unless-stopped
    networks:
      - ztcloud

  ztcl-panel:
    image: ${ZTCLP_IMAGE:-docker.io/library/python:3.12-alpine}
    container_name: ${ZTCLP_NAME:-ztcl-panel}
    ports:
      - "${ZTCLP_ADMIN_PORT:-8000}:8000"
    command: sh -c "export PATH=/ztcl/bin:\$PATH && python3 -m http.server 8000"
    volumes:
      - /opt/ztcl/bin:/ztcl/bin:ro
    restart: unless-stopped
    networks:
      - ztcloud

  #ztcldns:
  #  image: ${ZTCLDNS_IMAGE:-ztcldns:latest}
  #  container_name: ${ZTCLDNS_NAME:-ztcldns}
  #  environment:
  #    - BASE_DOMAIN=${BASE_DOMAIN:-ztcloud.ztcl}
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - "${DATA_PATH:-/opt/containers/sys}/coredns/hosts:/sync/hosts"
  #    - "${DATA_PATH:-/opt/containers/sys}/caddy/containers:/sync/caddy/containers"
  #  restart: unless-stopped
  #  networks:
  #    - ztcloud

networks:
  ztcloud:
    driver: bridge
